# Generated by Django 4.1.3 on 2022-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=23)),
                ('turi', models.CharField(max_length=23)),
                ('narxi', models.IntegerField(default=23)),
            ],
        ),
    ]
