# Generated by Django 4.1.3 on 2022-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noutbuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narxi', models.IntegerField(default=30)),
                ('davlati', models.CharField(max_length=30)),
                ('ishlasi', models.CharField(max_length=30)),
            ],
        ),
    ]
